---
# Setup/install tasks.
- include: setup.yml

# Vhost configuration.
- include: vhosts.yml

# Nginx setup.
- name: Copy nginx configuration in place.
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_path }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: 0644
  notify:
    - reload nginx

- name: Start nginx.
  command: "nginx"
