---
es_major_version: "1.x"
es_version: "1.7.3"
es_package: "elasticsearch-{{ es_version }}"
es_instance_name: node
es_cluster_name: cluster
es_start_service: true
es_restart_on_change: true
es_plugins_reinstall: false
es_plugins: [{name: "geocluster-facet", package: "geocluster-facet-0.0.12.jar", reinstall=true}]
es_scripts: false
es_user: elasticsearch
es_group: elasticsearch
es_config: {}
es_port: 9200
#Need to provide default directories
es_install_prefix: "/opt/elasticsearch/{es_version}"
es_pid_dir: "{{ es_install_prefix }}/{{ es_instance_name }}"
es_data_dir: "{{ es_install_prefix }}/lib/{{ es_instance_name }}"
es_log_dir: "{{ es_install_prefix }}/log/{{ es_instance_name }}"
es_work_dir: "{{ es_install_prefix }}/tmp/{{ es_instance_name }}"
es_plugin_dir: "{{ es_install_prefix }}/plugins"
es_conf_dir: "{{ es_install_prefix }}/conf/{{ es_instance_name }}"
sysd_script: "/usr/lib/systemd/system/elasticsearch.service"
init_script: "/etc/init.d/elasticsearch"

tmp_path: "/tmp"

default_file: "/etc/sysconfig/elasticsearch"
