---
es_major_version: "1.7"
es_version: "1.7.3"
es_package: "elasticsearch-{{ es_version }}"
es_instance_name: node
es_cluster_name: cluster
es_start_service: true
es_restart_on_change: true
es_plugins_reinstall: false
es_plugins: [{name: "geocluster-facet", package: "geocluster-facet-0.0.12.jar", reinstall=true}]
es_scripts: false
es_user: nlamti
es_group: nlamti
es_config: {}
es_port: 9200
#Need to provide default directories
es_install_prefix: "/opt/elasticsearch/{{ es_version }}"
es_pid_dir: "{{ es_install_prefix }}/{{ es_instance_name }}"
es_data_dir: "{{ es_install_prefix }}/lib/{{ es_instance_name }}"
es_log_dir: "{{ es_install_prefix }}/log/{{ es_instance_name }}"
es_work_dir: "{{ es_install_prefix }}/tmp/{{ es_instance_name }}"
es_plugin_dir: "{{ es_install_prefix }}/plugins"
es_conf_dir: "{{ es_install_prefix }}/config/{{ es_instance_name }}"
sysd_script: "/usr/lib/systemd/system/elasticsearch.service"
init_script: "/etc/init.d/elasticsearch"

es_use_repository : false
es_version_lock : false
es_package_url : "http://packages.elastic.co/elasticsearch/{{ es_major_version }}/centos/elasticsearch"

es_home : "/usr/share/elasticsearch"

tmp_path: "/tmp"

#default_file: "{{ es_install_prefix }}/{{ es_instance_name }}"
default_file: "/etc/default/elasticsearch"

