---
# This Playbook would deploy the whole mongodb cluster with replication.
- name: common
  hosts: all
  roles:
  - role: common

- name: Install MongoDB
  hosts: mongo_servers
  roles:
  - role: mongod_base

- name: Setup the Primary Node
  hosts: mongod_primary
  roles:
  - role: mongod_primary

- name: Configure the replicaset security across all nodes
  hosts: mongo_servers
  roles:
  - role: mongod_replicaset

- name: Add the nodes to the cluster
  hosts: mongod_slaves
  serial: 1
  roles:
  - role: mongod_replicaset_slaves

- name: Add mongo arbiters to the cluster
  hosts: mongod_arbiters
  serial: 1
  roles:
  - role: mongod_replicaset_arbiters
