---
# Used only for Debian/Ubuntu installation, as the -t option for apt.
nginx_default_release: ""

# Use the official Nginx PPA for Ubuntu, and the version to use if so.
nginx_ppa_use: false
nginx_ppa_version: stable

# The name of the nginx apt/yum package to install.
nginx_package_name: "nginx"

nginx_worker_processes: "1"
nginx_worker_connections: "1024"
nginx_multi_accept: "off"
##################################################################################

#nginx_install_prefix: "/opt/nginx/{{ nginx_version }}"
#nginx_error_log_path: "{{ nginx_install_prefix }}/log/nginx/error.log"
#nginx_access_log_path: "{{ nginx_install_prefix }}/log/nginx/access.log"
#nginx_sbin_path: "{{ nginx_install_prefix }}/sbin"
#nginx_conf_path: "{{ nginx_install_prefix }}/conf/conf.d"
#nginx_pidfile: "{{ nginx_install_prefix }}/nginx.pid"
#nginx_vhost_path: "{{ nginx_install_prefix }}/conf/conf.d"
#nginx_default_vhost_path: "{{ nginx_install_prefix }}/conf/default.conf"


#################################################################################



nginx_error_log: "/var/log/nginx/error.log warn"
nginx_access_log: "/var/log/nginx/access.log main buffer=16k"

nginx_sendfile: "on"
nginx_tcp_nopush: "on"
nginx_tcp_nodelay: "on"

nginx_keepalive_timeout: "65"
nginx_keepalive_requests: "100"

nginx_client_max_body_size: "64m"

nginx_proxy_cache_path: ""

nginx_extra_conf_options: ""
# Example extra main options, used within the main nginx's context:
#   nginx_extra_conf_options: |
#     env VARIABLE;
#     include /etc/nginx/main.d/*.conf;

nginx_extra_http_options: ""
# Example extra http options, printed inside the main server http config:
#    nginx_extra_http_options: |
#      proxy_buffering    off;
#      proxy_set_header   X-Real-IP $remote_addr;
#      proxy_set_header   X-Scheme $scheme;
#      proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
#      proxy_set_header   Host $http_host;

nginx_remove_default_vhost: true
nginx_vhosts:
# Example vhost below, showing all available options:
 - listen: "8080 default_server" # default: "80 default_server"
   server_name: "localhost" # default: N/A
   root: "/usr/share/nginx/html" # default: N/A
   index: "index.html index.htm" # default: "index.html index.htm"
   # Properties that are only added if defined:
   error_page: "500 502 503 504  /50x.html"
   #access_log: "/var/log"
   #error_log: "/var/error"
   #extra_parameters: "" # Can be used to add extra config blocks (multiline).
   locations :
        - path : /myels
          contents :
           - key : proxy_pass
             value : http://myels
           - key : server_name_in_redirect
             value : "on"

        #- path : /
        #  contents :
        #   - key: root
        #     value: /usr/share/nginx/html
        #   - key: index
        #     value: index.html index.htm
        #- path : /dev/
        #  contents :
        #   - key: alias
        #     value: /group/claims/cca-frontend-1.0.0-SNAPSHOT/cca-frontend-1.0.0-SNAPSHOT/dist/
        #- path : ~* ^/api/claims/(.*)
        #  contents :
        #   - key: proxy_pass
        #     value: http://127.0.0.1:9197/api/claims/$1$is_args$args
        #- path : ~* ^/api/bodyshops/(.*)
        #  contents :
        #   - key: proxy_pass
        #     value: http://127.0.0.1:9197/api/bodyshops/$1$is_args$args
        #- path : ~* ^/api/users/(.*)
        #  contents :
        #   - key: proxy_pass
        #     value: http://127.0.0.1:9198/api/users/$1$is_args$args
        #- path :  ~* ^/api/configs/(.*)
        #  contents :
        #   - key: proxy_pass
        #     value: proxy_pass http://127.0.0.1:9198/api/configs/$1$is_args$args

# - listen: "9080 default_server" # default: "80 default_server"
#   server_name: "172.17.0.2" # default: N/A
#   root: "/usr/share/nginx/html" # default: N/A
#   index: "index.html index.htm" # default: "index.html index.htm"
   # Properties that are only added if defined:
   #error_page: "/var/error1"
   #access_log: "/var/log1"
   #error_log: "/var/error1"
   #extra_parameters: "" # Can be used to add extra config blocks (multiline).

nginx_upstreams:
 - name: myels
   strategy: "ip_hash" #"least_conn", etc.
   servers: {
     "http://localhost:9201 ",
     "http://localhost:9200 ",
   }
