---
- name: restart nginx
  command: nginx -s quit ; nginx

- name: validate nginx configuration
  command: nginx -t -c /etc/nginx/nginx.conf
  changed_when: False

- name: reload nginx
  command: nginx -s reload
