---
dependencies: []

galaxy_info:
  author: "AXA-TECH"
  description: Nginx installation for Linux/UNIX.
  company: "AXA-TECH"
  license: "free"
  min_ansible_version: 1.8
  platforms:
    - name: EL
      versions:
      - 6
      - 7
    - name: Debian
      versions:
      - all
    - name: Ubuntu
      versions:
      - all
  galaxy_tags:
    - development
    - web
