---
# This Playbook runs all the common plays in the deployment
#- name: Create the hosts file for all machines
#  template: src=hosts.j2 dest=/etc/hosts

- name: Create the EPEL Repository.
  copy: src=local.repo dest=/etc/yum.repos.d/local.repo

- name: Create the mongod user
  user: name=mongod comment="MongoD"

- name: Create the data directory for the namenode metadata
  file: path={{ mongodb_datadir_prefix }} owner=mongod group=mongod state=directory

- name: Install the mongodb package
  yum: name={{ item }} state=installed
  with_items:
   - libselinux-python
   - mongodb-org
   - mongodb-org-server
   - bc
   - python-pip
   - ntp
   - tuned
  ignore_errors : yes
- name: Enable NTPD
  service: name=ntpd enabled=yes state=started

- name: Install the latest pymongo package
  pip: name=pymongo state=latest use_mirrors=no

# Disable transparent_hugepages
- name: Disable transparent_hugepages, create the profile directory for tuned (1/3)
  file: path=/etc/tune-profiles/no-thp/ state=directory

- name: Copy the tuned.conf to the new directory (2/3)
  copy: src=tuned.conf dest=/etc/tune-profiles/no-thp/tuned.conf mode="u=rwx,g=xr,o=x"

- name: Enable the new profile
  command: tuned-adm profile no-thp
