- name: Removing Old Plugins
  shell: bin/plugin --remove {{ item.name }}
    chdir={{ es_install_prefix }}/install
  when: item.name is defined and item.reinstall is defined and item.reinstall == True
  with_items: es_plugins
  ignore_errors: yes

- name: Upload Plugins packages
  copy: >
    src="{{ item.package }}"
    dest="{{ tmp_path}}"
  when: item.name is defined and item.package is defined
  with_items: es_plugins

- name: Installing Plugins
  shell: bin/plugin --url file:///tmp/{{ item.package }} --install {{ item.name }}
    chdir={{ es_install_prefix }}
  with_items: es_plugins
  when: item.name is defined and item.package is defined
  register: plugins_installed
  changed_when: "'Installed' in plugins_installed.stdout"
  failed_when: "plugins_installed.rc != 0 and plugins_installed.stdout.find('already exists. To update the plugin') == -1"
