---
- name: check-parameters
  sudo : yes
  include: checkParameters.yml

- name : install elasticsearch
  sudo : yes
  include: elasticsearch.yml
  
- name : check elasticsearch config 
  sudo : yes
  include: elasticsearch-config.yml

- name : script elasticsearch
  sudo : yes
  include: elasticsearch-scripts.yml
  when: es_scripts

- name : enable elasticsearch plugins
  sudo : yes
  include: elasticsearch-plugins.yml
  when: es_plugins is defined

- name : activate elasticsearch service
  sudo : yes 
  include: elasticsearch-service.yml

- meta: flush_handlers
